CREATE TABLE "GCG_4915_APRVL_CERT"(
 "GS_NUMBER" VARCHAR(7) NOT NULL ,
 "VEND_CUST" VARCHAR(6) NOT NULL ,
 "AMOUNT" DOUBLE NOT NULL ,
 "DATE_DUE" DATE NOT NULL ,
 "ORIGINATOR" VARCHAR(8) NOT NULL ,
 "APPROVER" VARCHAR(8),
 "APPROVED_DATE" DATETIME);